import type { Metadata } from "next";
import { Providers } from "./providers";
import { fontVariables } from "@/lib/font";
import { cn } from "@/lib/utils";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(fontVariables, "antialiased")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
